export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';

export const AUTH_SET_AUTHENTICATED = 'AUTH_SET_AUTHENTICATED';

export const COUPLE_SET_COUPLE = 'COUPLE_SET_COUPLE';

export const EXPENSE_SET_EXPENSE = 'EXPENSE_SET_EXPENSE';
export const EXPENSE_APPEND_EXPENSE = 'EXPENSE_APPEND_EXPENSE';
