export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_CONFIRM = 'AUTH_CONFIRM';

export const EXPENSE_CREATING = 'EXPENSE_CREATING';
export const EXPENSE_GETTING = 'EXPENSE_GETTING';
export const EXPENSE_DELETING = 'EXPENSE_DELETING';

